name: ios_fl_n_casinobarriere_3282
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  fl_chart: ^0.70.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  onesignal_flutter: ^5.3.0
  appsflyer_sdk: ^6.15.2
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.4.0
  app_tracking_transparency: ^2.0.6
  app_set_id: ^1.2.1
  flutter_asa_attribution: ^1.0.0
  http: ^1.3.0



flutter_native_splash:
  color: '#ffffff'
  image: images/l1.png
  ios_content_mode: scaleAspectFill

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/achieve/
    - assets/images/buttons/
    - assets/images/brain_exercise/
    - assets/images/mini_games/
    - assets/images/mini_games/memorize_posiition/