name: ios_fl_n_casinobarriere_3282
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/achieve/
    - assets/images/buttons/
    - assets/images/brain_exercise/
    - assets/images/mini_games/
    - assets/images/mini_games/memorize_posiition/